### ISSUE TITLE
How to get variables of each agent?

### ISSUE THREAD

**Issue by widhadyah** [projectmesa/mesa-examples#2]
Hi all,

I am using mesa for my program. I am trying to execute my Model Class, but I got AttributeError from the Agent Class. 

This is my script:

   ```
 class ComtrModel (Model):
        """ A model with some number of Agents"""
        def __init__(self,N):
            self.num_agents = N
            self.schedule = RandomActivation(self)
            for i in range (N):
                a = CommuterAgent(i)
                self.schedule.add(a)
    
    class CommuterAgent (Agent):
        def __init__(self, model):
            self.famsize = famsize
            self.distance = distance
            self.update_need = None
            
    
        def step(self):
            if  self.distance >= 10000:
                self.update_need = self.update_need()
                return
    
        def update_need (self, famsize):
            if self.famsize :
                self.famsize = famsize
                return
                prob_need()
```

How to get variables of each agent? I need to check it to make sure the model run properly.

So far this is my code to execute that:
```
for key, value in CommuterAgent.step(model):
    print(key, value)
```

But it returns ErrorAttribute : 'ComtrModel' object has no attribute 'distance'

**Comment by dmasad** [comment]
There are a few things going on here which may be causing problems.

Your agent class takes a `model` as an argument, but doesn't actually do anything with it; however, you're passing in a number, `i`, which looks like it ought to be an agent name. When you create a new agent within the `ComtrModel` class, it should probably look something like `a = CommuterAgent(i, self)` and the agent's init method should start with something like

```python
class CommuterAgent(Agent):
    def __init__(self, unique_id, model):
        self.unique_id = unique_id
        self.model = model
        # ...everything else...
```

Your agent's init function references the `famsize` and `distance` variables, but these don't seem to be defined anywhere.

It looks like you're trying to use `update_need` as the name for both a variable and a method. You define the `CommuterAgent`'s `update_need` method, but in init you assign `self.update_need = None`, which replaces the method with a `None` object. Also, in the `update_need` method itself, the line `prob_need()` is never actually reached, since you `return` above it.

Finally, I'm not sure what 'for key, value in CommuterAgent.step(model):' is doing; the function doesn't actually return anything, but you're trying to iterate over the result as though it were a tuple. 

If you want to make sure the model is running properly, I suggest starting with a bare skeleton of agents being activated, and slowly add one feature at a time. Alternatively, feel free to use of the examples, and start making modifications as needed.
